version: '2'

services:
  app:
    build: .
    image: jforge-app
    container_name: "jforge-app"
    volumes:
     - .:/opt/app-source:ro
    networks:
     - jforge-net

networks:
  jforge-net:
      driver: bridge
