version: '2'

services:
  app:
    build: .
    image: commando-app
    container_name: "commando-app"
    volumes:
     - .:/opt/app-source:ro
    networks:
     - commando-net

networks:
  commando-net:
      driver: bridge
